# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 03:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180216_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'\xc4\xb0\xc3\xa7erik'),
        ),
    ]
